service:
  name: "" # The name of the service, should be defined in the specific app-configs folder.
  hasHealthcheck: "true"
replicaCount: 1
image:
  repository: coco/annotations-publish-healthchecker
  pullPolicy: IfNotPresent
resources:
  requests:
    memory: 60Mi
  limits:
    memory: 128Mi